---
title: "Project 2 Group 4"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

## von Anna, Ann-Sophie und Jana

```{r, include=FALSE}
#Load required packages
library(knitr)
```

```{r setup, include=FALSE} 
#code and output not included in final file
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
```


## Load data

```{r }
NCI_TPW_gep_treated <- readRDS(url("https://ndownloader.figshare.com/files/14720180?private_link=db1411debcfbe2618d2f"))
NCI_TPW_gep_untreated <- readRDS(url("https://ndownloader.figshare.com/files/14720183?private_link=db1411debcfbe2618d2f"))
NCI_TPW_metadata <- read.delim("https://ndownloader.figshare.com/files/14720186?private_link=db1411debcfbe2618d2f")
NegLogGI50 <- readRDS(url("https://ndownloader.figshare.com/files/14720210?private_link=074e0120fe5e682f3d14"))
CCLE_basalexpression <- readRDS(url("https://ndownloader.figshare.com/files/14770127?private_link=fc0c71246dc192982a3c"))
CCLE_copynumber <- readRDS(url("https://ndownloader.figshare.com/files/14770130?private_link=fc0c71246dc192982a3c"))
CCLE_mutations <- readRDS(url("https://ndownloader.figshare.com/files/14770133?private_link=fc0c71246dc192982a3c"))
cellline_annotation <-read.delim("https://ndownloader.figshare.com/files/14768981?private_link=efb6a529eaf2d4dc6432")
drug_annotation <- read.delim("https://ndownloader.figshare.com/files/14768984?private_link=efb6a529eaf2d4dc6432")
```

# 1. Broad analysis

**Calculate fold change** due to drug treatment
```{r }
fold_changes <- NCI_TPW_gep_treated - NCI_TPW_gep_untreated
```

**Matrix annotation_of_celllines_per_drug** contains all names of celllines treated with each drug in a column (15 drugs, each in a seperated column containing all celllines treated with that drug)
```{r }
annotation_of_celllines_per_drug <- matrix(, nrow = 60, ncol = 0)

#to cbind all celllines of one drug in the annotation matrix, they need to have the same number of rows all columns #are filled to 60 rows with "NA"s and before that the actual number of rows gets stored in length_without_NAs

length_without_NAs <- c()

for (i in 1:15){
  columns_of_one_drug <- c(grep (drug_annotation$Drug[i], colnames(fold_changes), value = TRUE))
  length_without_NAs <- c(length_without_NAs, length(columns_of_one_drug))
  columns_of_one_drug <- c(columns_of_one_drug, rep(NA, 60-length(columns_of_one_drug)))
  annotation_of_celllines_per_drug <- cbind (annotation_of_celllines_per_drug, columns_of_one_drug)
}

#sort annotation alphabetically
colnames(annotation_of_celllines_per_drug) <- drug_annotation$Drug
annotation_of_celllines_per_drug <- annotation_of_celllines_per_drug [ , c(8, 1, 15, 7, 4, 14, 3, 5, 11, 6, 2, 12, 10, 13, 9)]
length_without_NAs <- length_without_NAs[c(8, 1, 15, 7, 4, 14, 3, 5, 11, 6, 2, 12, 10, 13, 9)]
```

**Coloring**
```{r }
#define a color palette with 15 chosen colors
color_palette <- c("aquamarine", "brown1", "forestgreen", "slategrey", "chartreuse", "darkgoldenrod1", "cadetblue","purple", "firebrick1", "deepskyblue", "gold", "violetred4", "deeppink", "plum2", "blue" )

#define vector with 15 colors each assigned to one drug
colors <- cbind(color_palette, colnames(annotation_of_celllines_per_drug))
colnames(colors) <- c("Color", "Drug")

#create vector containing each color name so often as the treated celllines with one drug
color_vector_all_drugs <- c()
for (i in 1:15){
  for (j in 1:length_without_NAs[i] )
  color_vector_all_drugs <- c(color_vector_all_drugs, colors [i, 1])
}
```

**Boxplot**
```{r }
boxplot(NCI_TPW_gep_untreated, xlab = "Celllines treated with different drugs",ylab = "Genexpression profile",vertical =  T, boxcol = color_vector_all_drugs)
```

**PCA**
```{r }
pca <- prcomp(fold_changes)

#color all celllines in PCA according to drug treatment
par(oma = c(1, 1, 1, 8))
plot(pca$rotation[,1], pca$rotation[,2], col = color_vector_all_drugs, pch = 19, xlab = "PC1", ylab = "PC2", main = "PCA with FC of all celllines treated with different drugs")
legend(x = 0.08, y = 0.15, legend = colors[, 2], col = colors[, 1], pch = 19, xpd = "TRUE")
```


# 2. Specific analysis: Erlotinib




